# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hipchat"
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["MojoTech"]
  s.date = "2011-10-19"
  s.description = "Ruby library to interact with HipChat"
  s.email = "gems@mojotech.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.textile"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "hipchat.gemspec",
    "lib/hipchat.rb",
    "lib/hipchat/capistrano.rb",
    "lib/hipchat/chef.rb",
    "lib/hipchat/rails3_tasks.rb",
    "lib/hipchat/railtie.rb",
    "lib/hipchat/connection.rb",
    "spec/hipchat_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/mojotech/hipchat"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby library to interact with HipChat"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<em-http-request>, ["~> 1.0.2"])
      s.add_runtime_dependency(%q<faraday>, ["~> 0.8.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<webmock>, ["~> 1.8.6"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<em-http-request>, ["~> 1.0.2"])
      s.add_dependency(%q<faraday>, ["~> 0.8.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<webmock>, ["~> 1.8.6"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<em-http-request>, ["~> 1.0.2"])
    s.add_dependency(%q<faraday>, ["~> 0.8.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<webmock>, ["~> 1.8.6"])
  end
end

